name: tempmail
description: TempMail - mail.cx temporary mail client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0
  ffi: ^2.1.3
  url_launcher: ^6.3.0
  flutter_rasp: ^7.1.0
  http_certificate_pinning: ^3.0.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/donate_qr.png
